/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c5b44324-fcf5-40f0-9bf8-7a30461d1cd6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yDDX0IYFk",
    "aws_user_pools_web_client_id": "4jv50c116g4ran9bas33mdsbeg",
    "oauth": {}
};


export default awsmobile;
